name: gif7005-env-final
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab
  - notebook
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - imbalanced-learn
  - xgboost
  - pip
  - pip:
      - jupytext
      - nbstripout
      - ydata-profiling
      - evidently
